version: '3.0'
services:

  automatic1111:
    build: ./services/automatic1111
    volumes:
      - /mnt/shared:/mnt/shared
    ports:
      - "8080:8080"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 'all'
              capabilities: [gpu]
    command: --ckpt-dir /mnt/shared/models --xformers --force-enable-xformers --listen --port 8080 --api 
    healthcheck:
        test: ["CMD", "curl", "-f", "http://0.0.0.0:8080/sdapi/v1/memory"]
        timeout: 10s
        retries: 10
    environment:
      PYTHONUNBUFFERED: 1
